baseurl = "https://sarusworld.github.io/"  
title = "Sarus World"

languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"

# number of words of summarized post content (default 70)
summaryLength = 70

# Define the number of posts per page
paginate = 10

# not pluralize title pages by default
pluralizelisttitles = false


[menu]

# Main menu
[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 1



[[menu.main]]
    name       = "Services"
    identifier = "menu.features"
    url        = "/services"
    weight     = 3



[[menu.main]]
    name       = "Profile"
    identifier = "menu.portfolio"
    url        = "/profile"
    weight     = 3


[[menu.main]]
    identifier = "contact"
    name       = "Contact"
    url        = "/contact/"
    weight     = 7


# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/SarusMarket/miniature-goggles"
    pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 2
    name = "Linkedin"
    url = "https://www.linkedin.com/in/shyam-prasad-arch/"
    pre = "<i class='fab fa-2x fa-linkedin'></i>"


[[menu.topbar]]
    weight = 3
    name = "Email"
    url = "mailto:sarusworld@outlook.com"
    pre = "<i class='fas fa-2x fa-envelope'></i>"

[params]
    # Social media
    facebook_site = "" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site = "GoHugoIO" # the Twitter handle of your site (without the '@')
    default_sharing_image = "img/sharing-default.png"


    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"



    about_us = "<p>Bengaluru</p>"
    copyright = "SarusWorld; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    dropdown_mouse_over = false

    disabled_logo = false
    logo_text = "Sarus World"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"
    contact_url = "/contact"
    address = """<p class="text-uppercase"><strong>Sarus Ltd.</strong>
        <br>South
        <br>
        <strong>India</strong>
      </p>
      """


# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">Contact us on sarusworld@outlook.com.</p>
      <p class="hidden-md hidden-lg"><a href="tel:+91" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
      <a href="mailto: sarusworld@outlook.com" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar

[params.carouselHomepage]
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more information take a look at the README.
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.features]
    enable = true
    cols = 3 # Default: 3, Available values 2,3,4,6
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more information take a look at the README.
